name: Sync
on:
  schedule:
  - cron: '0/30 * * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Sync with vidavidorra/.github
        run: |
          git remote add upstream https://github.com/vidavidorra/.github.git
          git fetch upstream
          git merge upstream/main --no-edit
          git push
