name: Sync
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.email '62569482+vidavidorra-bot@users.noreply.github.com'
          git config --global user.name 'vidavidorra[bot]'
      - name: Sync with vidavidorra/.github
        run: |
          git remote add upstream https://github.com/vidavidorra/.github.git
          git fetch upstream
          git merge upstream/main --no-edit
          git push
